<?php
namespace LlamaHire;

defined( 'ABSPATH' ) || exit;

/**
 * Dedicated permissions for jobs and sensitive candidate data.
 */
final class Capabilities {
	const OPTION              = 'llamahire_capabilities_version';
	const VIEW_APPLICATIONS   = 'llamahire_view_applications';
	const MANAGE_APPLICATIONS = 'llamahire_manage_applications';
	const EXPORT_APPLICATIONS = 'llamahire_export_applications';
	const DOWNLOAD_RESUMES    = 'llamahire_download_resumes';
	const RETRY_NOTIFICATIONS = 'llamahire_retry_notifications';

	public static function maybe_install() {
		if ( LLAMAHIRE_CAPABILITIES_VERSION !== (string) get_option( self::OPTION, '0' ) ) {
			self::install();
		}
	}

	/**
	 * Grant the complete hiring permission set to administrators.
	 *
	 * Other roles receive no access by default and may be configured explicitly.
	 */
	public static function install() {
		$role = get_role( 'administrator' );
		if ( $role ) {
			foreach ( self::all() as $capability ) {
				$role->add_cap( $capability );
			}
		}
		update_option( self::OPTION, LLAMAHIRE_CAPABILITIES_VERSION, false );
	}

	/**
	 * Remove LlamaHire capabilities from every role during uninstall.
	 */
	public static function remove() {
		foreach ( wp_roles()->roles as $role_name => $details ) {
			$role = get_role( $role_name );
			if ( $role ) {
				foreach ( self::all() as $capability ) {
					$role->remove_cap( $capability );
				}
			}
		}
		delete_option( self::OPTION );
	}

	/**
	 * All primitive capabilities owned by LlamaHire Free.
	 *
	 * @return string[]
	 */
	public static function all() {
		return array_merge(
			self::job_capabilities(),
			array(
				'manage_llamahire_departments',
				'edit_llamahire_departments',
				'delete_llamahire_departments',
				'assign_llamahire_departments',
				self::VIEW_APPLICATIONS,
				self::MANAGE_APPLICATIONS,
				self::EXPORT_APPLICATIONS,
				self::DOWNLOAD_RESUMES,
				self::RETRY_NOTIFICATIONS,
			)
		);
	}

	/**
	 * Primitive capabilities generated by the job post type.
	 *
	 * @return string[]
	 */
	public static function job_capabilities() {
		return array(
			'edit_llamahire_jobs',
			'edit_others_llamahire_jobs',
			'publish_llamahire_jobs',
			'read_private_llamahire_jobs',
			'delete_llamahire_jobs',
			'delete_private_llamahire_jobs',
			'delete_published_llamahire_jobs',
			'delete_others_llamahire_jobs',
			'edit_private_llamahire_jobs',
			'edit_published_llamahire_jobs',
		);
	}

	private function __construct() {}
}
